[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "truscanner"
version = "0.1.0"
description = "Open-Source Static Analysis for Privacy Data Flows"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "click>=8.1.8",
    "openai>=1.0.0",
    "presidio-analyzer>=2.2.0",
]

[project.optional-dependencies]
dev = [
    "twine",
    "build",
]

[project.scripts]
truscanner = "truscanner.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/truscanner"]